---
title: "Herramienta para el Análisis de Personajes Mitológicos"
subtitle: "Máster de Análisis de Datos Masivos en Economía y Empresa"
author: "Sergi Fornés"
output: pdf_document
urlcolor: "blue"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Guión

Entender la mitología es entender al ser humano. Diferentes culturas han creado mitos para responder cuestiones complejas de manera sencilla. En estos mitos aparecen personajes sobrenaturales y las relaciones que mantienen con los seres humanos.


En los mitos aparecen todo tipo de personajes, desde diosas del amor hasta monstruos devoradores de humanos. Dada esta diversidad aparecen preguntas interesantes, ¿diferentes culturas tienen personajes similares? ¿existen relaciones entre las características de los personajes? ¿y entre los mismos personajes?

Los objetivos de este trabajo son:

1. Crear un conjunto de datos de personajes mitológicos de diversas culturas.
2. Analizar el conjunto de datos.
3. Crear una herramienta de análisis de personajes mitológicos.

### Creación del conjunto de datos

El conjunto de datos se obtendrá utilizando herramientas de web-scraping en Python.  

Todos los datos se extraerán de la enciclopedia digital [Wikipedia](https://wikipedia.es). Hay que señalar que cualquier persona puede editar esta enciclopedia, por lo que es posible que el conjunto de datos tenga errores. Sin embargo, Wikipedia es una de las plataformas de contenido libre más completas de internet.  
Existen artículos en Wikipedia de prácticamente todos los personajes mitológicos. Estos artículos están clasificados en categorías similares, por lo que se navegará a través de estas categorías para obtener el texto disponible de los personajes. Además se añadirá información adicional de cada personaje en función de la categoría en la que se encuentre.  

Por otro lado, los artículos pueden tener enlaces a artículos de otros personajes, así que también se extraerá una matriz con estas relaciones.  

### Análisis del conjunto de datos

Se realizará un análisis exploratorio de los datos y se usarán técnicas de análisis de grafos sobre la matriz de enlaces para crear un índice de importancia de los personajes.  

La variable más importante de los personajes es el texto extraído de Wikipedia, así que también se aplicarán diversas técnicas de análisis de texto. Así mismo se aplicarán técnicas de análisis de grafos sobre las conclusiones del análisis de texto.

### Aplicación para la creación de personajes

Se creará una herramienta interactiva con la que poder analizar personajes o mitologías de diversas maneras. Por ejemplo, a partir de la palabra "mar", se podrá obtener un conjunto de características comunes a personajes mitológicos relacionados con el mar.