---
title: "Análisis de Personajes Mitológicos"
author: "Sergi Fornés"
subtitle: Trabajo Final de Máster
output:
  word_document: default
  pdf_document: default
classoption: twocolumn
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# formato tfm: http://destio.us.es/calvo/memoriatfe/MemoriaTFE_PedroLuque_2017Nov_librodigital.pdf
```


# Introducción

¿Porqué es importante la mitología? [Mitología => Esencia del ser humano]
¿Porqué es importante analizar los personajes mitológicos?


## asd

Entender la mitología es entender al ser humano. Diferentes culturas antiguas han creado mitos para responder cuestiones complejas de manera sencilla. En estos mitos aparecen personajes sobrenaturales y las relaciones que mantienen con los seres humanos.


En los mitos aparecen todo tipo de personajes, desde diosas del amor hasta monstruos devoradores de humanos. Dada esta diversidad aparecen preguntas interesantes, ¿diferentes culturas tienen personajes similares? ¿existen relaciones entre las características de diferentes personajes? ¿y entre las características de los mismos personajes?


Los objetivos de este trabajo son:

1. Crear un conjunto de datos de personajes mitológicos de diversas culturas.
2. Aplicar diversos algoritmos de aprendizaje automático para extraer conocimiento sobre mitologías y personajes mitológicos.

### Creación del conjunto de datos

El conjunto de datos se obtendrá utilizando librerías de web-scraping (`Beautiful Soup` y `Selenium`) de Python.  

Todos los datos se extraerán de la enciclopedia digital [Wikipedia](https://wikipedia.es). Hay que señalar que cualquier persona puede editar esta enciclopedia, por lo que es posible que el conjunto de datos tenga errores. Sin embargo, Wikipedia es una de las plataformas de contenido libre más completas de internet.  


Existen artículos en Wikipedia de prácticamente todos los personajes mitológicos. Estos artículos están clasificados en categorías similares, por lo que se navegará a través de estas categorías para obtener el texto disponible de los personajes. Además se añadirá información adicional de cada personaje en función de la categoría en la que se encuentre, como la mitología, la región, el continente, o el tipo de personaje (deidad, héroe, monstruo, ...).  

Este conjunto de datos tendrá una estructura de base de datos relacional ya que existen relaciones de muchos a muchos entre los personajes, mitologías y tipos de personaje. La base de datos constará de 5 entidades y 2 relaciones: Tabla de personajes mitológicos, tabla de mitologías, tabla de regiones, tabla de continentes, tabla de tipos de personaje, tabla de relación personaje-mitología y tabla de relación personaje-tipo.  


Por otro lado, los artículos de los personajes mitológicos están relacionados entre sí mediante enlaces. Se extraerá una matriz con estas relaciones con el fin de trabajar con grafos.  

### Análisis del conjunto de datos

Se realizará un análisis exploratorio de los datos y se usarán técnicas de análisis de grafos sobre la matriz de relaciones para crear índices de importancia de los personajes y analizar posibles relaciones entre diversas mitologías.  


La variable más importante de los personajes es el texto extraído de su artículo de Wikipedia, así que también se aplicarán diversos algoritmos de NLP para su análisis.

